kind: Pod
apiVersion: v1
metadata:
  name: env-test
spec: 
  containers:
  - name: nginx
    image: nginx
  resources:
  # This is soft limit
    requests:
      cpu: "100m"
      memory: "64Mi"
  # limits should equal or more than the requests i.e hard limit
    limits:
      cpu: "125m"
      memory: "100Mi"
